### ISSUE TITLE
Illegal state switching perspectives

### ISSUE THREAD

**Issue by mrbkt** [kestreltechnology/eclipse-kt-advance#5]
Choosing KT Advance perspective successfully presents the views, but also leads to an illegal state exception regarding selections, and presents error dialog.

```{java}
!ENTRY org.eclipse.ui.workbench 4 2 2016-12-25 15:59:57.479
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".
!STACK 0
java.lang.IllegalStateException: Need an underlying widget to be able to set the input.(Has the widget been disposed?)
     at org.eclipse.jface.viewers.StructuredViewer.setInput(StructuredViewer.java:1687)
     at com.kt.advance.statistics.AbstractStatisticsView.selectionChanged(AbstractStatisticsView.java:81)
     at org.eclipse.ui.internal.e4.compatibility.SelectionService.notifyListeners(SelectionService.java:271)
     at org.eclipse.ui.internal.e4.compatibility.SelectionService.notifyListeners(SelectionService.java:195)
     at org.eclipse.ui.internal.WorkbenchWindow$WWinPartService.partActivated(WorkbenchWindow.java:3003)
     at org.eclipse.ui.internal.WorkbenchPage$14.run(WorkbenchPage.java:4977)
     at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
     at org.eclipse.ui.internal.WorkbenchPage.firePartActivated(WorkbenchPage.java:4974)
     at org.eclipse.ui.internal.WorkbenchPage.access$19(WorkbenchPage.java:4962)
     at org.eclipse.ui.internal.WorkbenchPage$E4PartListener.partActivated(WorkbenchPage.java:210)
     at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$3.run(PartServiceImpl.java:250)
     at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
     at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.firePartActivated(PartServiceImpl.java:247)
     at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:757)
     at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.switchPerspective(PartServiceImpl.java:642)
     at org.eclipse.e4.ui.workbench.renderers.swt.PerspectiveStackRenderer.showTab(PerspectiveStackRenderer.java:106)
     at org.eclipse.e4.ui.workbench.renderers.swt.LazyStackRenderer$1.handleEvent(LazyStackRenderer.java:72)
     at org.eclipse.e4.ui.services.internal.events.UIEventHandler$1.run(UIEventHandler.java:40)
     at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:233)
     at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:145)
     at org.eclipse.swt.widgets.Display.syncExec(Display.java:4806)
     at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:211)
     at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:36)
     at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:201)
     at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
     at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
     at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
     at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
     at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135)
     at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78)
     at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39)
     at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:94)
     at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:60)
     at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
     at org.eclipse.e4.ui.model.application.ui.advanced.impl.PerspectiveStackImpl.setSelectedElement(PerspectiveStackImpl.java:135)
     at org.eclipse.e4.ui.model.application.ui.advanced.impl.PerspectiveStackImpl.setSelectedElement(PerspectiveStackImpl.java:1)
     at org.eclipse.ui.internal.WorkbenchPage.setPerspective(WorkbenchPage.java:4091)
     at org.eclipse.ui.handlers.ShowPerspectiveHandler.openPerspective(ShowPerspectiveHandler.java:147)
     at org.eclipse.ui.handlers.ShowPerspectiveHandler.openOther(ShowPerspectiveHandler.java:119)
     at org.eclipse.ui.handlers.ShowPerspectiveHandler.execute(ShowPerspectiveHandler.java:58)
     at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
     at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:498)
     at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
     at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:282)
     at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:264)
     at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
     at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
     at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
     at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:488)
     at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
     at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:196)
     at org.eclipse.e4.ui.workbench.addons.perspectiveswitcher.PerspectiveSwitcher.selectPerspective(PerspectiveSwitcher.java:632)
     at org.eclipse.e4.ui.workbench.addons.perspectiveswitcher.PerspectiveSwitcher.access$2(PerspectiveSwitcher.java:628)
     at org.eclipse.e4.ui.workbench.addons.perspectiveswitcher.PerspectiveSwitcher$7.widgetSelected(PerspectiveSwitcher.java:387)
     at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
     at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
     at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4248)
     at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1501)
     at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
     at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1509)
     at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1313)
     at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
     at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
     at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
     at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
     at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
     at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
     at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
     at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
     at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
     at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
     at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
     at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:498)
     at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
     at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
     at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
     at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```
![screen shot 2016-12-25 at 4 05 48 pm](https://cloud.githubusercontent.com/assets/23245160/21473031/0e930a62-cabc-11e6-9654-441a680c186a.png)

**Comment by mrbkt** [comment]
The same issue occurred when closing the Project Summary view.  

```{java}
!ENTRY org.eclipse.ui.workbench 4 2 2016-12-25 16:08:50.390
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".
!STACK 0
java.lang.IllegalStateException: Need an underlying widget to be able to set the input.(Has the widget been disposed?)
     at org.eclipse.jface.viewers.StructuredViewer.setInput(StructuredViewer.java:1687)
     at com.kt.advance.statistics.AbstractStatisticsView.selectionChanged(AbstractStatisticsView.java:81)
     at org.eclipse.ui.internal.e4.compatibility.SelectionService.notifyListeners(SelectionService.java:271)
     at org.eclipse.ui.internal.e4.compatibility.SelectionService.notifyListeners(SelectionService.java:195)
     at org.eclipse.ui.internal.WorkbenchWindow$WWinPartService.partActivated(WorkbenchWindow.java:3003)
     at org.eclipse.ui.internal.WorkbenchPage$14.run(WorkbenchPage.java:4977)
     at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
     at org.eclipse.ui.internal.WorkbenchPage.firePartActivated(WorkbenchPage.java:4974)
     at org.eclipse.ui.internal.WorkbenchPage.access$19(WorkbenchPage.java:4962)
     at org.eclipse.ui.internal.WorkbenchPage$E4PartListener.partActivated(WorkbenchPage.java:210)
     at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$3.run(PartServiceImpl.java:250)
     at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
     at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.firePartActivated(PartServiceImpl.java:247)
     at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:757)
     at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:682)
     at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:677)
     at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.hidePart(PartServiceImpl.java:1345)
     at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.hidePart(PartServiceImpl.java:1284)
     at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.closePart(StackRenderer.java:1289)
     at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.access$2(StackRenderer.java:1271)
     at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer$7.close(StackRenderer.java:1156)
     at org.eclipse.swt.custom.CTabFolder.onMouse(CTabFolder.java:1930)
     at org.eclipse.swt.custom.CTabFolder$1.handleEvent(CTabFolder.java:338)
     at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
     at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4248)
     at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1501)
     at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
     at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1509)
     at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1313)
     at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
     at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
     at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
     at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
     at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
     at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
     at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
     at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
     at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
     at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
     at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
     at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:498)
     at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
     at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
     at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
     at org.eclipse.equinox.launcher.Main.main(Main.java:1492)

```

**Comment by msiz** [comment]
Have been caused by lack of selection listener deregistration for disposed views.
